### ISSUE TITLE
Neos 4.2 Installation, Fehler, error - kannst du helfen?

### ISSUE THREAD

**Issue by acidhexe** [obisconcept/neos-php#5]
Console output:
Using version ^2.0 for obisconcept/neos-php
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - obisconcept/neos-php 2.0.2 requires neos/neos ^3.0.0 -> satisfiable by neos/neos[3.0.0, 3.0.1, 3.0.10, 3.0.11, 3.0.12, 3.0
.13, 3.0.14, 3.0.15, 3.0.16, 3.0.17, 3.0.18, 3.0.19, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.9, 3.0.x-dev, 3.1.0, 3
.1.1, 3.1.10, 3.1.11, 3.1.12, 3.1.13, 3.1.14, 3.1.15, 3.1.16, 3.1.17, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.7, 3.1.8, 3.1.9, 3.
1.x-dev, 3.2.0, 3.2.1, 3.2.10, 3.2.11, 3.2.12, 3.2.13, 3.2.2, 3.2.3, 3.2.4, 3.2.5, 3.2.6, 3.2.7, 3.2.8, 3.2.9, 3.2.x-dev, 3.3.0,
 3.3.1, 3.3.10, 3.3.11, 3.3.12, 3.3.13, 3.3.14, 3.3.15, 3.3.16, 3.3.17, 3.3.18, 3.3.19, 3.3.2, 3.3.20, 3.3.3, 3.3.4, 3.3.5, 3.3.
6, 3.3.7, 3.3.8, 3.3.9, 3.3.x-dev] but these conflict with your requirements or minimum-stability.
    - obisconcept/neos-php 2.0.1 requires neos/neos ~3.0.0 -> satisfiable by neos/neos[3.0.0, 3.0.1, 3.0.10, 3.0.11, 3.0.12, 3.0
.13, 3.0.14, 3.0.15, 3.0.16, 3.0.17, 3.0.18, 3.0.19, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.9, 3.0.x-dev] but these conflict with your requirements or minimum-stability.
    - obisconcept/neos-php 2.0.0 requires neos/neos ~3.0.0 -> satisfiable by neos/neos[3.0.0, 3.0.1, 3.0.10, 3.0.11, 3.0.12, 3.0
.13, 3.0.14, 3.0.15, 3.0.16, 3.0.17, 3.0.18, 3.0.19, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.9, 3.0.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for obisconcept/neos-php ^2.0 -> satisfiable by obisconcept/neos-php[2.0.0, 2.0.1, 2.0.2].

Installation failed, reverting ./composer.json to its original content.

**Comment by MCStreetguy** [comment]
As you can see in the Composer error message, the plugin needs Neos in version ^3.0. Neos 4.x is currently not supported, but an update is planned for this year. I close this issue as it is not a real bug.
